"""Seed content for Biology."""

SUBJECT = {
    "name": "Biology",
    "slug": "biology",
    "icon": "biotech",
    "color": "#43A047",
    "description": "Cells, the human body, plant life and genetics.",
    "chapters": [
        {
            "name": "Cell — The Unit of Life",
            "slug": "cell-the-unit-of-life",
            "description": "Cell theory, organelles and cell division.",
            "topics": ["Cell structure", "Organelles", "Cell division"],
            "concepts": [
                {
                    "kind": "concept",
                    "title": "Cell theory",
                    "body": "All living organisms are made of cells, the cell is the basic structural and functional unit of life, and every cell arises from a pre-existing cell. Prokaryotic cells lack a true nucleus; eukaryotic cells have one.",
                },
                {
                    "kind": "concept",
                    "title": "Organelles and their jobs",
                    "body": "Mitochondria release energy as ATP, ribosomes build proteins, the endoplasmic reticulum transports material, lysosomes digest waste and chloroplasts (plants only) carry out photosynthesis.",
                },
                {
                    "kind": "point",
                    "title": "Revision points",
                    "body": "• Lysosomes are the 'suicide bags' of the cell\n• Plant cells have a cellulose cell wall and a large vacuole\n• Mitosis gives two identical daughter cells; meiosis gives four gametes",
                },
                {
                    "kind": "example",
                    "title": "Why are mitochondria called powerhouses?",
                    "body": "They oxidise glucose products to release energy stored as ATP, the currency the cell spends on all its activities.",
                },
            ],
            "questions": [
                {
                    "topic": "Organelles",
                    "text": "Which organelle is known as the powerhouse of the cell?",
                    "options": ["Ribosome", "Mitochondrion", "Lysosome", "Golgi body"],
                    "correct": "B",
                    "explanation": "Mitochondria release energy in the form of ATP.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Cell structure",
                    "text": "A cell without a true nucleus is called:",
                    "options": ["Eukaryotic", "Prokaryotic", "Somatic", "Gamete"],
                    "correct": "B",
                    "explanation": "Prokaryotic cells, such as bacteria, have no nuclear membrane.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Organelles",
                    "text": "Protein synthesis in a cell takes place at the:",
                    "options": ["Ribosomes", "Vacuole", "Nucleolus", "Centrosome"],
                    "correct": "A",
                    "explanation": "Ribosomes are the site of protein synthesis.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Organelles",
                    "text": "Lysosomes are called suicide bags because they:",
                    "options": ["Store food", "Contain digestive enzymes", "Make proteins", "Store water"],
                    "correct": "B",
                    "explanation": "Their hydrolytic enzymes can digest the cell's own worn-out parts.",
                    "difficulty": "medium",
                },
                {
                    "topic": "Cell division",
                    "text": "The type of cell division that produces gametes is:",
                    "options": ["Mitosis", "Meiosis", "Binary fission", "Budding"],
                    "correct": "B",
                    "explanation": "Meiosis halves the chromosome number and produces four gametes.",
                    "difficulty": "medium",
                },
            ],
        },
        {
            "name": "Human Body Systems",
            "slug": "human-body-systems",
            "description": "Digestive, respiratory, circulatory and nervous systems.",
            "topics": ["Digestion", "Respiration", "Circulation", "Nervous system"],
            "concepts": [
                {
                    "kind": "concept",
                    "title": "Circulatory system",
                    "body": "The human heart has four chambers: two atria and two ventricles. Deoxygenated blood goes to the lungs through the pulmonary artery and returns oxygenated through pulmonary veins — a double circulation.",
                },
                {
                    "kind": "concept",
                    "title": "Digestion and respiration",
                    "body": "Digestion begins in the mouth with salivary amylase and completes in the small intestine, where villi absorb nutrients. Respiration exchanges gases in the alveoli of the lungs and releases energy from glucose in cells.",
                },
                {
                    "kind": "point",
                    "title": "Revision points",
                    "body": "• Largest gland in the body: liver\n• Absorption of digested food: small intestine (villi)\n• Functional unit of the kidney: nephron",
                },
            ],
            "questions": [
                {
                    "topic": "Circulation",
                    "text": "How many chambers does the human heart have?",
                    "options": ["Two", "Three", "Four", "Five"],
                    "correct": "C",
                    "explanation": "Two atria and two ventricles.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Digestion",
                    "text": "The largest gland in the human body is the:",
                    "options": ["Pancreas", "Liver", "Thyroid", "Salivary gland"],
                    "correct": "B",
                    "explanation": "The liver is the largest gland and secretes bile.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Respiration",
                    "text": "Exchange of gases in the lungs occurs in the:",
                    "options": ["Bronchi", "Trachea", "Alveoli", "Pleura"],
                    "correct": "C",
                    "explanation": "Alveoli provide a large, thin, moist surface for gaseous exchange.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Digestion",
                    "text": "Most absorption of digested food happens in the:",
                    "options": ["Stomach", "Small intestine", "Large intestine", "Oesophagus"],
                    "correct": "B",
                    "explanation": "Villi in the small intestine absorb nutrients into the blood.",
                    "difficulty": "medium",
                },
                {
                    "topic": "Nervous system",
                    "text": "The structural and functional unit of the nervous system is the:",
                    "options": ["Nephron", "Neuron", "Alveolus", "Axon"],
                    "correct": "B",
                    "explanation": "The neuron (nerve cell) transmits impulses.",
                    "difficulty": "medium",
                },
            ],
        },
        {
            "name": "Plant Biology",
            "slug": "plant-biology",
            "description": "Photosynthesis, transpiration and plant tissues.",
            "topics": ["Photosynthesis", "Transport in plants", "Plant tissues"],
            "concepts": [
                {
                    "kind": "concept",
                    "title": "Photosynthesis",
                    "body": "Green plants use light energy trapped by chlorophyll to convert carbon dioxide and water into glucose, releasing oxygen. It takes place mainly in the chloroplasts of leaf mesophyll cells.",
                },
                {
                    "kind": "formula",
                    "title": "Photosynthesis equation",
                    "body": "6CO₂ + 6H₂O --light, chlorophyll--> C₆H₁₂O₆ + 6O₂",
                },
                {
                    "kind": "concept",
                    "title": "Transport in plants",
                    "body": "Xylem carries water and minerals upward from the roots; phloem transports food made in the leaves to the rest of the plant. Transpiration through the stomata creates the pull that lifts water.",
                },
                {
                    "kind": "point",
                    "title": "Revision points",
                    "body": "• Stomata control gas exchange and transpiration\n• Chlorophyll is the green pigment absorbing light\n• Phloem transport (translocation) needs energy",
                },
            ],
            "questions": [
                {
                    "topic": "Photosynthesis",
                    "text": "The green pigment responsible for photosynthesis is:",
                    "options": ["Carotene", "Chlorophyll", "Xanthophyll", "Anthocyanin"],
                    "correct": "B",
                    "explanation": "Chlorophyll in chloroplasts absorbs light energy.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Photosynthesis",
                    "text": "Which gas is released during photosynthesis?",
                    "options": ["Carbon dioxide", "Nitrogen", "Oxygen", "Hydrogen"],
                    "correct": "C",
                    "explanation": "Water is split and oxygen is released as a by-product.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Transport in plants",
                    "text": "Water and minerals are transported in plants through the:",
                    "options": ["Phloem", "Xylem", "Cambium", "Cortex"],
                    "correct": "B",
                    "explanation": "Xylem conducts water and dissolved minerals upward.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Transport in plants",
                    "text": "Loss of water as vapour from the aerial parts of a plant is called:",
                    "options": ["Transpiration", "Translocation", "Guttation", "Respiration"],
                    "correct": "A",
                    "explanation": "Transpiration occurs mainly through the stomata.",
                    "difficulty": "medium",
                },
                {
                    "topic": "Plant tissues",
                    "text": "Food prepared in leaves is transported by:",
                    "options": ["Xylem", "Phloem", "Epidermis", "Pith"],
                    "correct": "B",
                    "explanation": "Translocation of food occurs through the phloem.",
                    "difficulty": "medium",
                },
            ],
        },
        {
            "name": "Genetics",
            "slug": "genetics",
            "description": "Heredity, Mendel's laws, DNA and variation.",
            "topics": ["Mendel's laws", "DNA", "Sex determination"],
            "concepts": [
                {
                    "kind": "concept",
                    "title": "Mendel's experiments",
                    "body": "Mendel crossed pea plants and found that traits are controlled by pairs of factors (genes). The law of dominance explains a 3:1 phenotypic ratio in the F2 generation of a monohybrid cross.",
                },
                {
                    "kind": "concept",
                    "title": "DNA and chromosomes",
                    "body": "DNA is a double helix of nucleotides carrying the genetic code. Humans have 23 pairs of chromosomes; the 23rd pair determines sex, XX in females and XY in males.",
                },
                {
                    "kind": "point",
                    "title": "Revision points",
                    "body": "• Monohybrid F2 ratio 3:1; dihybrid 9:3:3:1\n• Genotype is the gene make-up, phenotype the visible trait\n• The father's chromosome decides the child's sex",
                },
            ],
            "questions": [
                {
                    "topic": "Mendel's laws",
                    "text": "Mendel performed his classic experiments on:",
                    "options": ["Maize", "Pea plants", "Fruit flies", "Rats"],
                    "correct": "B",
                    "explanation": "Mendel used the garden pea, Pisum sativum.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Mendel's laws",
                    "text": "The phenotypic ratio of an F2 monohybrid cross is:",
                    "options": ["1:1", "3:1", "9:3:3:1", "1:2:1"],
                    "correct": "B",
                    "explanation": "Dominant to recessive phenotypes appear in a 3:1 ratio.",
                    "difficulty": "medium",
                },
                {
                    "topic": "DNA",
                    "text": "The number of chromosome pairs in a human somatic cell is:",
                    "options": ["21", "22", "23", "46"],
                    "correct": "C",
                    "explanation": "23 pairs, i.e. 46 chromosomes in total.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Sex determination",
                    "text": "In humans, the sex chromosomes of a male are:",
                    "options": ["XX", "XY", "YY", "XO"],
                    "correct": "B",
                    "explanation": "Males are XY; females are XX.",
                    "difficulty": "easy",
                },
                {
                    "topic": "DNA",
                    "text": "The full form of DNA is:",
                    "options": ["Deoxyribonucleic acid", "Dinucleic acid", "Diribonucleic acid", "Deoxyribose nitrate"],
                    "correct": "A",
                    "explanation": "DNA stands for deoxyribonucleic acid.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Mendel's laws",
                    "text": "The observable characteristic of an organism is its:",
                    "options": ["Genotype", "Phenotype", "Allele", "Gamete"],
                    "correct": "B",
                    "explanation": "Phenotype is the visible expression of the genotype.",
                    "difficulty": "medium",
                },
            ],
        },
        {
            "name": "Life Processes",
            "slug": "life-processes",
            "description": "Nutrition, excretion and control in living things.",
            "topics": ["Nutrition", "Excretion"],
            "concepts": [],
            "questions": [],
        },
        {
            "name": "Ecology",
            "slug": "ecology",
            "description": "Ecosystems, food chains and conservation.",
            "topics": ["Ecosystem", "Food chains"],
            "concepts": [],
            "questions": [],
        },
    ],
}
