"""Seed content for Chemistry."""

SUBJECT = {
    "name": "Chemistry",
    "slug": "chemistry",
    "icon": "science",
    "color": "#00897B",
    "description": "Matter, atomic structure, the periodic table and reactions.",
    "chapters": [
        {
            "name": "Matter in Our Surroundings",
            "slug": "matter-in-our-surroundings",
            "description": "States of matter, changes of state and mixtures.",
            "topics": ["States of matter", "Change of state", "Mixtures"],
            "concepts": [
                {
                    "kind": "concept",
                    "title": "States of matter",
                    "body": "Matter exists as solid, liquid and gas depending on how strongly its particles are held together. Solids have fixed shape and volume, liquids have fixed volume but take the shape of the container, and gases fill the whole container because their particles move freely.",
                },
                {
                    "kind": "concept",
                    "title": "Changes of state",
                    "body": "Heating supplies energy that overcomes the forces between particles. Melting and boiling absorb latent heat at a constant temperature; sublimation converts a solid directly to vapour (for example camphor and dry ice).",
                },
                {"kind": "formula", "title": "Density", "body": "Density = mass / volume (kg m⁻³ or g cm⁻³)"},
                {
                    "kind": "example",
                    "title": "Why does evaporation cool?",
                    "body": "Escaping molecules take latent heat from the liquid left behind, so the remaining liquid and its surroundings cool down — this is why we sweat.",
                },
                {
                    "kind": "point",
                    "title": "Revision points",
                    "body": "• Pure water boils at 373 K (100 °C) at 1 atm\n• A solution is a homogeneous mixture\n• Latent heat causes no temperature change",
                },
            ],
            "questions": [
                {
                    "topic": "States of matter",
                    "text": "Which state of matter has a definite volume but no definite shape?",
                    "options": ["Solid", "Liquid", "Gas", "Plasma"],
                    "correct": "B",
                    "explanation": "A liquid keeps its volume but takes the shape of its container.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Change of state",
                    "text": "The boiling point of pure water at atmospheric pressure is:",
                    "options": ["273 K", "300 K", "373 K", "400 K"],
                    "correct": "C",
                    "explanation": "100 °C = 100 + 273 = 373 K.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Change of state",
                    "text": "The direct conversion of a solid into vapour is called:",
                    "options": ["Condensation", "Sublimation", "Fusion", "Diffusion"],
                    "correct": "B",
                    "explanation": "Sublimation, shown by camphor, naphthalene and dry ice.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Mixtures",
                    "text": "Which of the following is a homogeneous mixture?",
                    "options": ["Sand and water", "Oil and water", "Salt solution", "Smoke"],
                    "correct": "C",
                    "explanation": "A salt solution has a uniform composition throughout, so it is homogeneous.",
                    "difficulty": "medium",
                },
                {
                    "topic": "Change of state",
                    "text": "Evaporation causes cooling because the escaping molecules:",
                    "options": [
                        "Release heat",
                        "Absorb latent heat from the liquid",
                        "Increase pressure",
                        "Decrease volume",
                    ],
                    "correct": "B",
                    "explanation": "Molecules leaving the surface carry away latent heat, lowering the temperature of the remaining liquid.",
                    "difficulty": "medium",
                },
            ],
        },
        {
            "name": "Atoms and Molecules",
            "slug": "atoms-and-molecules",
            "description": "Atomic structure, mole concept and chemical formulae.",
            "topics": ["Atomic structure", "Mole concept", "Valency"],
            "concepts": [
                {
                    "kind": "concept",
                    "title": "Structure of the atom",
                    "body": "An atom has a nucleus of protons (positive) and neutrons (neutral) surrounded by electrons (negative). The atomic number equals the number of protons; the mass number is protons plus neutrons.",
                },
                {
                    "kind": "concept",
                    "title": "Mole concept",
                    "body": "One mole of any substance contains Avogadro's number, 6.022 × 10²³, of particles and has a mass in grams equal to its atomic or molecular mass.",
                },
                {
                    "kind": "formula",
                    "title": "Moles",
                    "body": "n = given mass / molar mass ; number of particles = n × 6.022 × 10²³",
                },
                {
                    "kind": "example",
                    "title": "Molar mass of water",
                    "body": "H₂O = (2 × 1) + 16 = 18 g/mol, so 18 g of water is one mole and contains 6.022 × 10²³ molecules.",
                },
                {
                    "kind": "point",
                    "title": "Revision points",
                    "body": "• Isotopes have the same atomic number but different mass numbers\n• Electrons hardly contribute to atomic mass\n• Valency of oxygen is 2, of hydrogen 1",
                },
            ],
            "questions": [
                {
                    "topic": "Atomic structure",
                    "text": "The particle that carries a negative charge in an atom is the:",
                    "options": ["Proton", "Neutron", "Electron", "Positron"],
                    "correct": "C",
                    "explanation": "Electrons carry a charge of −1.6 × 10⁻¹⁹ C.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Mole concept",
                    "text": "Avogadro's number is:",
                    "options": ["6.022 × 10²³", "6.022 × 10²²", "3.0 × 10⁸", "1.6 × 10⁻¹⁹"],
                    "correct": "A",
                    "explanation": "One mole contains 6.022 × 10²³ particles.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Mole concept",
                    "text": "The molar mass of water (H₂O) is:",
                    "options": ["16 g/mol", "18 g/mol", "20 g/mol", "22 g/mol"],
                    "correct": "B",
                    "explanation": "2(1) + 16 = 18 g/mol.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Atomic structure",
                    "text": "Atoms of the same element with different numbers of neutrons are called:",
                    "options": ["Isobars", "Isotopes", "Ions", "Allotropes"],
                    "correct": "B",
                    "explanation": "Isotopes share the atomic number but differ in mass number.",
                    "difficulty": "medium",
                },
                {
                    "topic": "Valency",
                    "text": "The chemical formula of calcium chloride is:",
                    "options": ["CaCl", "CaCl₂", "Ca₂Cl", "Ca₂Cl₃"],
                    "correct": "B",
                    "explanation": "Ca has valency 2 and Cl valency 1, so the formula is CaCl₂.",
                    "difficulty": "medium",
                },
            ],
        },
        {
            "name": "Periodic Table",
            "slug": "periodic-table",
            "description": "Periodic law, groups, periods and periodic trends.",
            "topics": ["Periodic law", "Groups and periods", "Periodic trends"],
            "concepts": [
                {
                    "kind": "concept",
                    "title": "Modern periodic law",
                    "body": "Properties of elements are a periodic function of their atomic number. The modern table has 18 groups and 7 periods; elements in a group have the same number of valence electrons and hence similar chemistry.",
                },
                {
                    "kind": "concept",
                    "title": "Periodic trends",
                    "body": "Across a period the nuclear charge rises while the shell stays the same, so atomic radius decreases and electronegativity increases. Down a group new shells are added, so radius increases and metallic character increases.",
                },
                {
                    "kind": "point",
                    "title": "Revision points",
                    "body": "• Group 1 = alkali metals, Group 17 = halogens, Group 18 = noble gases\n• Fluorine is the most electronegative element\n• Metallic character decreases across a period",
                },
            ],
            "questions": [
                {
                    "topic": "Periodic law",
                    "text": "The modern periodic table arranges elements in order of increasing:",
                    "options": ["Atomic mass", "Atomic number", "Density", "Valency"],
                    "correct": "B",
                    "explanation": "Moseley's modern periodic law uses atomic number.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Groups and periods",
                    "text": "Elements of group 18 are known as:",
                    "options": ["Alkali metals", "Halogens", "Noble gases", "Transition metals"],
                    "correct": "C",
                    "explanation": "Group 18 contains the chemically inert noble gases.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Periodic trends",
                    "text": "Moving left to right across a period, the atomic radius generally:",
                    "options": ["Increases", "Decreases", "Stays constant", "First increases then decreases"],
                    "correct": "B",
                    "explanation": "Increasing nuclear charge in the same shell pulls electrons closer, reducing the radius.",
                    "difficulty": "medium",
                },
                {
                    "topic": "Periodic trends",
                    "text": "The most electronegative element is:",
                    "options": ["Oxygen", "Chlorine", "Fluorine", "Nitrogen"],
                    "correct": "C",
                    "explanation": "Fluorine has the highest electronegativity, about 4.0 on the Pauling scale.",
                    "difficulty": "medium",
                },
                {
                    "topic": "Groups and periods",
                    "text": "How many periods does the modern periodic table have?",
                    "options": ["5", "6", "7", "8"],
                    "correct": "C",
                    "explanation": "There are 7 horizontal periods and 18 vertical groups.",
                    "difficulty": "hard",
                },
            ],
        },
        {
            "name": "Chemical Reactions",
            "slug": "chemical-reactions",
            "description": "Types of reactions, balancing equations, acids and bases.",
            "topics": ["Types of reactions", "Balancing equations", "Acids and bases"],
            "concepts": [
                {
                    "kind": "concept",
                    "title": "Types of chemical reactions",
                    "body": "Common types are combination, decomposition, displacement, double displacement and redox. Oxidation is loss of electrons (or gain of oxygen) and reduction is the reverse; they always occur together.",
                },
                {
                    "kind": "concept",
                    "title": "Acids, bases and pH",
                    "body": "Acids release H⁺ ions in water, bases release OH⁻. The pH scale runs 0–14: below 7 is acidic, 7 is neutral and above 7 is basic. Acid + base → salt + water is neutralisation.",
                },
                {"kind": "formula", "title": "Neutralisation", "body": "HCl + NaOH → NaCl + H₂O"},
                {
                    "kind": "example",
                    "title": "Balancing an equation",
                    "body": "Fe + H₂O → Fe₃O₄ + H₂ balances as 3Fe + 4H₂O → Fe₃O₄ + 4H₂, keeping atoms of each element equal on both sides.",
                },
                {
                    "kind": "point",
                    "title": "Revision points",
                    "body": "• Mass is conserved, so equations must be balanced\n• Respiration is an exothermic reaction\n• Photosynthesis is endothermic",
                },
            ],
            "questions": [
                {
                    "topic": "Types of reactions",
                    "text": "CaO + H₂O → Ca(OH)₂ is an example of a:",
                    "options": [
                        "Decomposition reaction",
                        "Combination reaction",
                        "Displacement reaction",
                        "Redox reaction",
                    ],
                    "correct": "B",
                    "explanation": "Two reactants combine into a single product, so it is a combination reaction.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Acids and bases",
                    "text": "The pH of a neutral solution at 25 °C is:",
                    "options": ["0", "7", "10", "14"],
                    "correct": "B",
                    "explanation": "Pure water is neutral with pH 7.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Acids and bases",
                    "text": "Which gas is produced when a metal reacts with a dilute acid?",
                    "options": ["Oxygen", "Hydrogen", "Carbon dioxide", "Nitrogen"],
                    "correct": "B",
                    "explanation": "Metal + dilute acid → salt + hydrogen gas.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Types of reactions",
                    "text": "Loss of electrons during a reaction is called:",
                    "options": ["Reduction", "Oxidation", "Neutralisation", "Hydrolysis"],
                    "correct": "B",
                    "explanation": "Oxidation is loss of electrons; reduction is gain of electrons.",
                    "difficulty": "medium",
                },
                {
                    "topic": "Balancing equations",
                    "text": "In the balanced equation 3Fe + 4H₂O → Fe₃O₄ + xH₂, the value of x is:",
                    "options": ["2", "3", "4", "6"],
                    "correct": "C",
                    "explanation": "Eight hydrogen atoms on the left require 4H₂ on the right.",
                    "difficulty": "hard",
                },
                {
                    "topic": "Acids and bases",
                    "text": "Reaction of an acid with a base to form salt and water is called:",
                    "options": ["Oxidation", "Neutralisation", "Decomposition", "Corrosion"],
                    "correct": "B",
                    "explanation": "Neutralisation: HCl + NaOH → NaCl + H₂O.",
                    "difficulty": "medium",
                },
            ],
        },
        {
            "name": "Metals and Non-metals",
            "slug": "metals-and-non-metals",
            "description": "Properties, reactivity series and corrosion.",
            "topics": ["Properties", "Reactivity series"],
            "concepts": [],
            "questions": [],
        },
        {
            "name": "Carbon and its Compounds",
            "slug": "carbon-and-its-compounds",
            "description": "Covalent bonding, hydrocarbons and functional groups.",
            "topics": ["Hydrocarbons", "Functional groups"],
            "concepts": [],
            "questions": [],
        },
    ],
}
