"""Seed content for Mathematics."""

SUBJECT = {
    "name": "Mathematics",
    "slug": "mathematics",
    "icon": "functions",
    "color": "#F4511E",
    "description": "Number system, arithmetic, ratio and algebra.",
    "chapters": [
        {
            "name": "Number System",
            "slug": "number-system",
            "description": "Natural, rational and irrational numbers, HCF and LCM.",
            "topics": ["Types of numbers", "HCF and LCM", "Divisibility"],
            "concepts": [
                {
                    "kind": "concept",
                    "title": "Classifying numbers",
                    "body": "Natural numbers count objects, integers add negatives and zero, rational numbers can be written as p/q with q ≠ 0, and irrational numbers such as √2 and π cannot. Together they form the real numbers.",
                },
                {"kind": "formula", "title": "HCF and LCM", "body": "HCF × LCM = product of the two numbers"},
                {
                    "kind": "example",
                    "title": "LCM of 12 and 18",
                    "body": "12 = 2² × 3 and 18 = 2 × 3². LCM takes the highest powers: 2² × 3² = 36; HCF takes the lowest: 2 × 3 = 6. Check: 6 × 36 = 216 = 12 × 18.",
                },
                {
                    "kind": "point",
                    "title": "Revision points",
                    "body": "• A number is divisible by 3 if its digit sum is divisible by 3\n• 0 is neither positive nor negative\n• √2 is irrational",
                },
            ],
            "questions": [
                {
                    "topic": "Types of numbers",
                    "text": "Which of the following is an irrational number?",
                    "options": ["4/5", "√2", "0.75", "−3"],
                    "correct": "B",
                    "explanation": "√2 cannot be written as a ratio of two integers.",
                    "difficulty": "easy",
                },
                {
                    "topic": "HCF and LCM",
                    "text": "The LCM of 12 and 18 is:",
                    "options": ["6", "24", "36", "72"],
                    "correct": "C",
                    "explanation": "12 = 2²×3, 18 = 2×3²; LCM = 2²×3² = 36.",
                    "difficulty": "easy",
                },
                {
                    "topic": "HCF and LCM",
                    "text": "The HCF of 24 and 36 is:",
                    "options": ["4", "6", "12", "18"],
                    "correct": "C",
                    "explanation": "Common factors give 2² × 3 = 12.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Divisibility",
                    "text": "Which number is divisible by 3?",
                    "options": ["124", "235", "342", "457"],
                    "correct": "C",
                    "explanation": "3 + 4 + 2 = 9, which is divisible by 3.",
                    "difficulty": "medium",
                },
                {
                    "topic": "HCF and LCM",
                    "text": "If the HCF of two numbers is 6 and their LCM is 36, the product of the numbers is:",
                    "options": ["42", "108", "216", "252"],
                    "correct": "C",
                    "explanation": "Product = HCF × LCM = 6 × 36 = 216.",
                    "difficulty": "hard",
                },
            ],
        },
        {
            "name": "Percentage",
            "slug": "percentage",
            "description": "Percentage change, profit and loss, simple interest.",
            "topics": ["Percentage basics", "Profit and loss", "Interest"],
            "concepts": [
                {
                    "kind": "concept",
                    "title": "Percentage as a fraction of 100",
                    "body": "x% means x/100. To find a percentage of a quantity, multiply by x/100; to express a as a percentage of b, compute (a/b) × 100.",
                },
                {
                    "kind": "formula",
                    "title": "Profit, loss and interest",
                    "body": "Profit % = (Profit / CP) × 100\nLoss % = (Loss / CP) × 100\nSI = P R T / 100",
                },
                {
                    "kind": "example",
                    "title": "Profit percentage",
                    "body": "CP = ₹400, SP = ₹500 → Profit = ₹100 → Profit % = (100/400) × 100 = 25%.",
                },
                {
                    "kind": "point",
                    "title": "Revision points",
                    "body": "• Profit and loss percentages are always on cost price\n• A 20% rise followed by a 20% fall gives a net 4% loss\n• 1/8 = 12.5%",
                },
            ],
            "questions": [
                {
                    "topic": "Percentage basics",
                    "text": "What is 15% of 200?",
                    "options": ["15", "20", "30", "45"],
                    "correct": "C",
                    "explanation": "200 × 15/100 = 30.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Profit and loss",
                    "text": "An article bought for ₹400 is sold for ₹500. The profit percentage is:",
                    "options": ["20%", "25%", "30%", "40%"],
                    "correct": "B",
                    "explanation": "Profit = 100; % = (100/400) × 100 = 25%.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Interest",
                    "text": "The simple interest on ₹1000 at 10% per annum for 2 years is:",
                    "options": ["₹100", "₹200", "₹210", "₹1200"],
                    "correct": "B",
                    "explanation": "SI = PRT/100 = 1000 × 10 × 2 / 100 = ₹200.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Percentage basics",
                    "text": "If a number is increased by 20% and then decreased by 20%, the net change is:",
                    "options": ["No change", "4% decrease", "4% increase", "2% decrease"],
                    "correct": "B",
                    "explanation": "100 → 120 → 96, a net 4% decrease.",
                    "difficulty": "medium",
                },
                {
                    "topic": "Profit and loss",
                    "text": "A shopkeeper sells an item at ₹270 after a 10% loss. The cost price was:",
                    "options": ["₹280", "₹297", "₹300", "₹310"],
                    "correct": "C",
                    "explanation": "0.9 × CP = 270 → CP = ₹300.",
                    "difficulty": "hard",
                },
            ],
        },
        {
            "name": "Ratio and Proportion",
            "slug": "ratio-and-proportion",
            "description": "Ratios, proportion, average, time and work.",
            "topics": ["Ratio", "Proportion", "Average"],
            "concepts": [
                {
                    "kind": "concept",
                    "title": "Ratio and proportion",
                    "body": "A ratio a : b compares two like quantities. Four quantities are in proportion when a : b = c : d, which gives ad = bc. Dividing a quantity in the ratio a : b means splitting it into a/(a+b) and b/(a+b) parts.",
                },
                {
                    "kind": "formula",
                    "title": "Average and work",
                    "body": "Average = sum of observations / number of observations\nWork done = rate × time",
                },
                {
                    "kind": "example",
                    "title": "Divide ₹500 in the ratio 2 : 3",
                    "body": "Total parts = 5, so the shares are 500 × 2/5 = ₹200 and 500 × 3/5 = ₹300.",
                },
                {
                    "kind": "point",
                    "title": "Revision points",
                    "body": "• Ratios have no units\n• If a : b = 2 : 3, then a = 2k and b = 3k\n• Speed = distance / time",
                },
            ],
            "questions": [
                {
                    "topic": "Ratio",
                    "text": "The ratio 4 : 6 in its simplest form is:",
                    "options": ["1 : 2", "2 : 3", "3 : 4", "4 : 5"],
                    "correct": "B",
                    "explanation": "Dividing both terms by 2 gives 2 : 3.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Ratio",
                    "text": "₹500 divided between A and B in the ratio 2 : 3 gives B:",
                    "options": ["₹200", "₹250", "₹300", "₹350"],
                    "correct": "C",
                    "explanation": "B's share = 500 × 3/5 = ₹300.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Average",
                    "text": "The average of 10, 20, 30 and 40 is:",
                    "options": ["20", "25", "30", "35"],
                    "correct": "B",
                    "explanation": "(10 + 20 + 30 + 40)/4 = 100/4 = 25.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Proportion",
                    "text": "If 3 : 5 = x : 20, then x equals:",
                    "options": ["9", "10", "12", "15"],
                    "correct": "C",
                    "explanation": "3/5 = x/20 → x = 12.",
                    "difficulty": "medium",
                },
                {
                    "topic": "Average",
                    "text": "A can finish a job in 10 days and B in 15 days. Working together they finish it in:",
                    "options": ["5 days", "6 days", "8 days", "12 days"],
                    "correct": "B",
                    "explanation": "Combined rate = 1/10 + 1/15 = 1/6, so 6 days.",
                    "difficulty": "hard",
                },
            ],
        },
        {
            "name": "Algebra",
            "slug": "algebra",
            "description": "Linear and quadratic equations, identities.",
            "topics": ["Linear equations", "Quadratic equations", "Identities"],
            "concepts": [
                {
                    "kind": "concept",
                    "title": "Solving linear equations",
                    "body": "An equation stays true when the same operation is applied to both sides. Collect like terms, isolate the variable, and check by substitution.",
                },
                {
                    "kind": "formula",
                    "title": "Key results",
                    "body": "(a + b)² = a² + 2ab + b²\na² − b² = (a + b)(a − b)\nx = [−b ± √(b² − 4ac)] / 2a",
                },
                {
                    "kind": "example",
                    "title": "Solve 2x + 3 = 11",
                    "body": "2x = 11 − 3 = 8, so x = 4. Substituting back: 2(4) + 3 = 11. ✔",
                },
                {
                    "kind": "point",
                    "title": "Revision points",
                    "body": "• Discriminant b² − 4ac decides the nature of the roots\n• Sum of roots = −b/a, product = c/a\n• Equal roots when b² = 4ac",
                },
            ],
            "questions": [
                {
                    "topic": "Linear equations",
                    "text": "Solve for x: 2x + 3 = 11.",
                    "options": ["2", "3", "4", "7"],
                    "correct": "C",
                    "explanation": "2x = 8, so x = 4.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Identities",
                    "text": "Expand (a + b)²:",
                    "options": ["a² + b²", "a² + 2ab + b²", "a² − 2ab + b²", "a² + ab + b²"],
                    "correct": "B",
                    "explanation": "(a + b)² = a² + 2ab + b².",
                    "difficulty": "easy",
                },
                {
                    "topic": "Quadratic equations",
                    "text": "The roots of x² − 5x + 6 = 0 are:",
                    "options": ["1 and 6", "2 and 3", "−2 and −3", "5 and 6"],
                    "correct": "B",
                    "explanation": "Factorising: (x − 2)(x − 3) = 0.",
                    "difficulty": "medium",
                },
                {
                    "topic": "Quadratic equations",
                    "text": "The sum of the roots of ax² + bx + c = 0 is:",
                    "options": ["b/a", "−b/a", "c/a", "−c/a"],
                    "correct": "B",
                    "explanation": "Sum of roots = −b/a and product = c/a.",
                    "difficulty": "medium",
                },
                {
                    "topic": "Quadratic equations",
                    "text": "A quadratic equation has equal roots when:",
                    "options": ["b² > 4ac", "b² < 4ac", "b² = 4ac", "b = 0"],
                    "correct": "C",
                    "explanation": "A zero discriminant, b² − 4ac = 0, gives two equal real roots.",
                    "difficulty": "hard",
                },
            ],
        },
        {
            "name": "Geometry",
            "slug": "geometry",
            "description": "Lines, triangles, circles and mensuration.",
            "topics": ["Triangles", "Circles"],
            "concepts": [],
            "questions": [],
        },
        {
            "name": "Trigonometry",
            "slug": "trigonometry",
            "description": "Ratios, identities and heights and distances.",
            "topics": ["Trigonometric ratios", "Identities"],
            "concepts": [],
            "questions": [],
        },
    ],
}
