"""Seed content for Physics."""

SUBJECT = {
    "name": "Physics",
    "slug": "physics",
    "icon": "bolt",
    "color": "#3F51B5",
    "description": "Motion, forces, energy, electricity and modern physics.",
    "chapters": [
        {
            "name": "Units & Measurements",
            "slug": "units-and-measurements",
            "description": "SI units, dimensions, significant figures and errors.",
            "topics": ["Units", "Dimensions", "Errors"],
            "concepts": [
                {
                    "kind": "concept",
                    "title": "Physical quantities and units",
                    "body": "A physical quantity is measured as a number multiplied by a unit. The SI system uses seven base units: metre (length), kilogram (mass), second (time), ampere (current), kelvin (temperature), mole (amount of substance) and candela (luminous intensity). All other units are derived from these.",
                },
                {
                    "kind": "concept",
                    "title": "Dimensional analysis",
                    "body": "Writing a quantity in terms of mass (M), length (L) and time (T) gives its dimensional formula. Only quantities with the same dimensions can be added or equated, which makes dimensional analysis a quick way to check a formula.",
                },
                {"kind": "formula", "title": "Speed", "body": "v = distance / time  →  [v] = L T⁻¹"},
                {"kind": "formula", "title": "Force", "body": "F = m a  →  [F] = M L T⁻²"},
                {
                    "kind": "formula",
                    "title": "Relative error",
                    "body": "Relative error = Δa / a ; Percentage error = (Δa / a) × 100",
                },
                {
                    "kind": "example",
                    "title": "Check the formula T = 2π√(l/g)",
                    "body": "[√(l/g)] = √(L / (L T⁻²)) = √(T²) = T. The right-hand side has the dimension of time, so the formula is dimensionally consistent.",
                },
                {
                    "kind": "point",
                    "title": "Revision points",
                    "body": "• 1 light year ≈ 9.46 × 10¹⁵ m\n• Angle and strain are dimensionless\n• Dimensional analysis cannot find dimensionless constants such as 2π",
                },
            ],
            "questions": [
                {
                    "topic": "Units",
                    "text": "Which of the following is a base SI unit?",
                    "options": ["Newton", "Joule", "Kelvin", "Watt"],
                    "correct": "C",
                    "explanation": "Kelvin is the SI base unit of thermodynamic temperature; newton, joule and watt are derived units.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Dimensions",
                    "text": "The dimensional formula of force is:",
                    "options": ["M L T⁻¹", "M L T⁻²", "M L² T⁻²", "M L⁻¹ T⁻²"],
                    "correct": "B",
                    "explanation": "Force = mass × acceleration = M × L T⁻² = M L T⁻².",
                    "difficulty": "easy",
                },
                {
                    "topic": "Dimensions",
                    "text": "Which pair of quantities has the same dimensions?",
                    "options": ["Work and power", "Work and energy", "Force and momentum", "Speed and acceleration"],
                    "correct": "B",
                    "explanation": "Work and energy are both M L² T⁻², measured in joules.",
                    "difficulty": "medium",
                },
                {
                    "topic": "Errors",
                    "text": "The number of significant figures in 0.00250 is:",
                    "options": ["2", "3", "5", "6"],
                    "correct": "B",
                    "explanation": "Leading zeros are not significant; 2, 5 and the trailing 0 are, giving three significant figures.",
                    "difficulty": "medium",
                },
                {
                    "topic": "Errors",
                    "text": "A length is measured as 25.0 cm with an absolute error of 0.5 cm. The percentage error is:",
                    "options": ["0.2%", "0.5%", "2%", "5%"],
                    "correct": "C",
                    "explanation": "(0.5 / 25.0) × 100 = 2%.",
                    "difficulty": "medium",
                },
                {
                    "topic": "Units",
                    "text": "One light year is approximately:",
                    "options": ["9.46 × 10¹² m", "9.46 × 10¹⁵ m", "3.00 × 10⁸ m", "1.50 × 10¹¹ m"],
                    "correct": "B",
                    "explanation": "Light travels 3 × 10⁸ m/s for about 3.15 × 10⁷ s in a year, giving ≈ 9.46 × 10¹⁵ m.",
                    "difficulty": "hard",
                },
            ],
        },
        {
            "name": "Motion",
            "slug": "motion",
            "description": "Distance, displacement, speed, velocity, acceleration and graphs.",
            "topics": ["Speed and velocity", "Acceleration", "Equations of motion"],
            "concepts": [
                {
                    "kind": "concept",
                    "title": "Distance and displacement",
                    "body": "Distance is the total path length covered and is always positive. Displacement is the straight-line change in position and has both magnitude and direction, so it can be zero even when distance is not.",
                },
                {
                    "kind": "concept",
                    "title": "Speed, velocity and acceleration",
                    "body": "Average speed is total distance divided by total time. Velocity is displacement per unit time and is a vector. Acceleration is the rate of change of velocity; it is negative (retardation) when the body slows down.",
                },
                {"kind": "formula", "title": "Average speed", "body": "Average speed = total distance / total time"},
                {
                    "kind": "formula",
                    "title": "Equations of motion",
                    "body": "v = u + a t\ns = u t + ½ a t²\nv² = u² + 2 a s",
                },
                {
                    "kind": "example",
                    "title": "A body travels 20 m in 4 s",
                    "body": "Average speed = 20 / 4 = 5 m/s.",
                },
                {
                    "kind": "example",
                    "title": "Car accelerating from rest",
                    "body": "A car starts from rest with a = 2 m/s² for 5 s: v = 0 + 2 × 5 = 10 m/s and s = 0 + ½ × 2 × 25 = 25 m.",
                },
                {
                    "kind": "point",
                    "title": "Revision points",
                    "body": "• Slope of a distance–time graph is speed\n• Slope of a velocity–time graph is acceleration\n• Area under a velocity–time graph is displacement",
                },
            ],
            "questions": [
                {
                    "topic": "Speed and velocity",
                    "text": "A body travels 20 m in 4 seconds. What is its average speed?",
                    "options": ["4 m/s", "5 m/s", "8 m/s", "10 m/s"],
                    "correct": "B",
                    "explanation": "Average speed = distance / time = 20 m / 4 s = 5 m/s.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Speed and velocity",
                    "text": "A runner completes one lap of a circular track and returns to the start. His displacement is:",
                    "options": [
                        "Equal to the circumference",
                        "Half the circumference",
                        "Zero",
                        "Equal to the diameter",
                    ],
                    "correct": "C",
                    "explanation": "Start and end positions coincide, so the displacement is zero even though the distance equals the circumference.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Equations of motion",
                    "text": "A car starting from rest accelerates uniformly at 2 m/s². Its velocity after 5 s is:",
                    "options": ["5 m/s", "10 m/s", "20 m/s", "25 m/s"],
                    "correct": "B",
                    "explanation": "v = u + at = 0 + 2 × 5 = 10 m/s.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Acceleration",
                    "text": "The slope of a velocity–time graph gives:",
                    "options": ["Displacement", "Distance", "Acceleration", "Momentum"],
                    "correct": "C",
                    "explanation": "Slope = change in velocity / change in time = acceleration.",
                    "difficulty": "medium",
                },
                {
                    "topic": "Equations of motion",
                    "text": "A body moving at 20 m/s is brought to rest in 4 s. Its retardation is:",
                    "options": ["4 m/s²", "5 m/s²", "10 m/s²", "80 m/s²"],
                    "correct": "B",
                    "explanation": "a = (v − u)/t = (0 − 20)/4 = −5 m/s², i.e. a retardation of 5 m/s².",
                    "difficulty": "medium",
                },
                {
                    "topic": "Equations of motion",
                    "text": "A stone is dropped from rest. Taking g = 10 m/s², the distance fallen in 3 s is:",
                    "options": ["30 m", "45 m", "60 m", "90 m"],
                    "correct": "B",
                    "explanation": "s = ½ g t² = ½ × 10 × 9 = 45 m.",
                    "difficulty": "hard",
                },
            ],
        },
        {
            "name": "Force and Laws of Motion",
            "slug": "force-and-laws-of-motion",
            "description": "Newton's laws, inertia, momentum and friction.",
            "topics": ["Newton's laws", "Momentum", "Friction"],
            "concepts": [
                {
                    "kind": "concept",
                    "title": "Newton's three laws",
                    "body": "First law: a body stays at rest or in uniform motion unless a net external force acts on it (inertia). Second law: the net force equals the rate of change of momentum, F = ma. Third law: for every action there is an equal and opposite reaction on a different body.",
                },
                {
                    "kind": "concept",
                    "title": "Momentum and impulse",
                    "body": "Momentum p = mv measures the 'quantity of motion'. Impulse is force × time and equals the change in momentum, which is why a longer contact time reduces the force felt in a collision.",
                },
                {"kind": "formula", "title": "Second law", "body": "F = m a = Δp / Δt"},
                {
                    "kind": "formula",
                    "title": "Friction",
                    "body": "f = μ N, where μ is the coefficient of friction and N the normal reaction",
                },
                {
                    "kind": "example",
                    "title": "Force on a 5 kg body",
                    "body": "A 5 kg body accelerates at 3 m/s². F = ma = 5 × 3 = 15 N.",
                },
                {
                    "kind": "point",
                    "title": "Revision points",
                    "body": "• Momentum is conserved when no external force acts\n• Action and reaction never cancel: they act on different bodies\n• Mass measures inertia",
                },
            ],
            "questions": [
                {
                    "topic": "Newton's laws",
                    "text": "Newton's second law of motion relates force to:",
                    "options": ["Displacement", "Rate of change of momentum", "Kinetic energy", "Work done"],
                    "correct": "B",
                    "explanation": "F = Δp/Δt; for constant mass this reduces to F = ma.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Newton's laws",
                    "text": "The force needed to accelerate a 5 kg body at 3 m/s² is:",
                    "options": ["8 N", "15 N", "1.67 N", "45 N"],
                    "correct": "B",
                    "explanation": "F = ma = 5 × 3 = 15 N.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Momentum",
                    "text": "The SI unit of linear momentum is:",
                    "options": ["kg m/s", "kg m/s²", "N m", "J s⁻¹"],
                    "correct": "A",
                    "explanation": "p = mv, so the unit is kilogram metre per second (also written N s).",
                    "difficulty": "easy",
                },
                {
                    "topic": "Newton's laws",
                    "text": "A passenger falls forward when a moving bus stops suddenly. This is explained by:",
                    "options": ["Inertia of motion", "Inertia of rest", "Conservation of energy", "Friction"],
                    "correct": "A",
                    "explanation": "The upper body tends to continue moving forward — inertia of motion.",
                    "difficulty": "medium",
                },
                {
                    "topic": "Friction",
                    "text": "A block of mass 10 kg rests on a surface with μ = 0.2 (g = 10 m/s²). The limiting friction is:",
                    "options": ["2 N", "10 N", "20 N", "100 N"],
                    "correct": "C",
                    "explanation": "f = μN = 0.2 × (10 × 10) = 20 N.",
                    "difficulty": "medium",
                },
                {
                    "topic": "Momentum",
                    "text": "A 0.5 kg ball moving at 10 m/s is stopped in 0.1 s. The average force applied is:",
                    "options": ["5 N", "25 N", "50 N", "100 N"],
                    "correct": "C",
                    "explanation": "F = Δp/Δt = (0.5 × 10)/0.1 = 50 N.",
                    "difficulty": "hard",
                },
            ],
        },
        {
            "name": "Work, Energy and Power",
            "slug": "work-energy-and-power",
            "description": "Work done, kinetic and potential energy, power and efficiency.",
            "topics": ["Work", "Energy", "Power"],
            "concepts": [
                {
                    "kind": "concept",
                    "title": "Work and energy",
                    "body": "Work is done when a force displaces a body along the direction of the force: W = F s cos θ. Energy is the capacity to do work; kinetic energy comes from motion and potential energy from position.",
                },
                {
                    "kind": "concept",
                    "title": "Conservation of energy",
                    "body": "Energy is neither created nor destroyed, only converted. For a freely falling body the sum of kinetic and potential energy stays constant when air resistance is ignored.",
                },
                {
                    "kind": "formula",
                    "title": "Work, energy, power",
                    "body": "W = F s cos θ\nKE = ½ m v²\nPE = m g h\nP = W / t",
                },
                {
                    "kind": "example",
                    "title": "Power of a lifting machine",
                    "body": "Lifting a 20 kg load through 5 m in 10 s (g = 10 m/s²): W = mgh = 1000 J, so P = 1000/10 = 100 W.",
                },
                {
                    "kind": "point",
                    "title": "Revision points",
                    "body": "• No work is done when force is perpendicular to displacement\n• 1 kWh = 3.6 × 10⁶ J\n• Doubling speed makes kinetic energy four times larger",
                },
            ],
            "questions": [
                {
                    "topic": "Work",
                    "text": "The SI unit of work is:",
                    "options": ["Watt", "Joule", "Newton", "Pascal"],
                    "correct": "B",
                    "explanation": "Work = force × displacement = newton metre = joule.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Energy",
                    "text": "The kinetic energy of a 2 kg body moving at 3 m/s is:",
                    "options": ["3 J", "6 J", "9 J", "18 J"],
                    "correct": "C",
                    "explanation": "KE = ½mv² = ½ × 2 × 9 = 9 J.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Power",
                    "text": "A machine does 1000 J of work in 10 s. Its power is:",
                    "options": ["10 W", "100 W", "1000 W", "10 000 W"],
                    "correct": "B",
                    "explanation": "P = W/t = 1000/10 = 100 W.",
                    "difficulty": "easy",
                },
                {
                    "topic": "Work",
                    "text": "A porter carries a suitcase horizontally at constant speed. The work done by the upward force he applies is:",
                    "options": ["Positive", "Negative", "Zero", "Equal to mgh"],
                    "correct": "C",
                    "explanation": "The force is vertical while the displacement is horizontal, so cos 90° = 0 and no work is done.",
                    "difficulty": "medium",
                },
                {
                    "topic": "Energy",
                    "text": "If the speed of a body is doubled, its kinetic energy becomes:",
                    "options": ["Twice", "Three times", "Four times", "Unchanged"],
                    "correct": "C",
                    "explanation": "KE ∝ v², so doubling v multiplies the energy by four.",
                    "difficulty": "medium",
                },
                {
                    "topic": "Power",
                    "text": "One kilowatt-hour equals:",
                    "options": ["3.6 × 10³ J", "3.6 × 10⁶ J", "10³ J", "10⁶ J"],
                    "correct": "B",
                    "explanation": "1 kWh = 1000 W × 3600 s = 3.6 × 10⁶ J.",
                    "difficulty": "hard",
                },
            ],
        },
        {
            "name": "Gravitation",
            "slug": "gravitation",
            "description": "Universal law of gravitation, weight and free fall.",
            "topics": ["Universal law", "Free fall"],
            "concepts": [],
            "questions": [],
        },
        {
            "name": "Heat",
            "slug": "heat",
            "description": "Temperature, specific heat and transfer of heat.",
            "topics": ["Temperature", "Specific heat"],
            "concepts": [],
            "questions": [],
        },
        {
            "name": "Sound",
            "slug": "sound",
            "description": "Wave motion, speed of sound and echo.",
            "topics": ["Waves", "Echo"],
            "concepts": [],
            "questions": [],
        },
        {
            "name": "Light",
            "slug": "light",
            "description": "Reflection, refraction, lenses and mirrors.",
            "topics": ["Reflection", "Refraction"],
            "concepts": [],
            "questions": [],
        },
        {
            "name": "Electricity",
            "slug": "electricity",
            "description": "Current, Ohm's law, resistance and power.",
            "topics": ["Ohm's law", "Circuits"],
            "concepts": [],
            "questions": [],
        },
        {
            "name": "Magnetism",
            "slug": "magnetism",
            "description": "Magnetic fields, electromagnets and induction.",
            "topics": ["Magnetic field", "Induction"],
            "concepts": [],
            "questions": [],
        },
        {
            "name": "Modern Physics",
            "slug": "modern-physics",
            "description": "Atomic structure, photoelectric effect and nuclei.",
            "topics": ["Atomic structure", "Nuclei"],
            "concepts": [],
            "questions": [],
        },
    ],
}
